---
title: "zipcode"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
source(here::here("R/read_zipcode.R"))
```

`read_zipcode()` で日本郵便が公開する住所データファイルを読み込みます。

`read_zipcode_jigyosyo()`

```{r}
df_zip_pref45 <- 
  read_zipcode(here::here("data-raw/japanpost_kogaki/45MIYAZA.CSV")) %>% 
  select(jis_code, zip_code, prefecture, city, street,
         starts_with("is_"),
         status,
         modify_type)
```

```{r}
df_zip_pref45 %>% 
  count(is_street_duplicate)
```

```{r}
df_zip_pref45 %>% 
  filter(is_street_duplicate == FALSE) %>% 
  pull(zip_code) %>% 
  sample(1)
df_zip_pref45 %>% 
  filter(is_street_duplicate == TRUE) %>% 
  pull(street) %>% 
  sample(1)

df_zip_pref45 %>% 
  filter(zip_code %in% c("8892154") |
         stringr::str_detect(street, "高岡町五町")) %>%
  tidyr::extract(street, into = c("street", "street_sub"), regex = "(.+)(\\(.+\\))") %>% 
  mutate(street_sub = stringr::str_remove_all(street_sub, "\\(|\\)"))

df_zip_pref45 %>% 
  count(is_zipcode_duplicate)
```

`zipcode_spacer()` は郵便番号のような7桁の数値に対し、3桁目と4桁目の間にハイフンを入れたり、また、ハイフンを取り除きます。

```{r}
zipcode_spacer("3100004")
zipcode_spacer(3100004)

# ハイフンを取り除くには remove引数でTRUEを指定します
zipcode_spacer("310-0004", remove = TRUE)
```

